language: python
python:
- 3.5
install:
- pip install -r requirements.txt
script:
- mkdocs build
env:
  global:
  - GITHUB_REPO: atomisthq/atomisthq.github.io
  - secure: avZof6zOvqzTz3HIWKUCCVnNtN1kUJJUulrRPqQNukYpvK6pPFmv9bv0KPZeTWr7fC88fnptjm2SbgXhtNkZxv0pqRP2Zy5yzgwZfQlHJKWb2DSA7D65kCCejHvmyIx6fbpfG4A7OMGHKP1yoUOkgm3WXmXXfckKZ0ADiEnvx1kenhF4MfMNoAxBIX/xX9NtKxWejvF/Go18ePxVW/Y+UpOQ9l8n9z3RZQ2+ocoSP/7RhQTNnJgHO+S9UtnRVN5yBkUTiLU9I7+NpvcLbBekLGyS0Vh979HT0oDU/LAbpXWIfGFm97CY7zn7pCa3vkPtbGs/+FVAo10ZYuLYYrzlxipbrEGPBAQl0eFbIu7Fl/aQWsGYM0/kLiLKFl+/8NgB+eblGb7F8CyUKWgpARlGLc50Ht0C/QBREzRT7bLoDfRxsGc90vQ+mw1D6P7w1vi6Ib3XeVw+zSKvtgb8ul+lqbuShkiH2x4gE+M/1NLByWTIsVdEqiyLK9up+xYOLw7X3swaXLTEjNVTi8havQEABn+cVZPpiOSQcIyF3ydW7kVOqAzc3ewrYPasgOTj2humYTwpAm3Cv49OqahRKA03S7iGzNCzLn1uTX6EsftztCV4OHHHZrsBNB3Kyni/OJh0hg8tc23EXPdBSy2bQFFyeHCG5oyMsy6S+aEZmC08968=
deploy:
  provider: releases
  api_key:
    secure: pyaxQjhyUN2Lr91v2jAbqBCd6G+e91zJvKxvkWRL+DQR0i0mnmUS04iTkB2uEykystixqVKT6XYif/S12NAH03SFFwrgiaSF8hQgNG9l40nLhE00/mnxajezFVp98vwivEs+2CSy8CTRhZw9H3yT6A5ja7dN+t7EyrFs1gfP8VKEoJyrEajkIh8nlELDmoISKcRPUlEqjMUm2Ve/axaQoxbu5JKJcpSJ+X8gwv5bFU0JpFtAZcsxu7KaDFgtujaKavzt+HiXvDgvcawpTzuAdoZBW0hEEbjmAOnbRd5RHpg+1mvbkOdP5Or5bfsrf6ohW994pGSmGi7mNsCB8SV0oEMBeVTVObqoKLAvN5QF49Zm4k95SurGJCDuG/JQbiDWUE203mA4vwZZE5i1FnkqR71U0ufKm1ERu5U6dSh8fQNQShHld+8nscrWb9QC7WTrd4kXVt2ZhexrKV1TYCzspuA12Dr2t/4FC/Pr9vj9nb8f/J53OcrXJvmYJcIxJnbhmK2mbhEYLT4TzoxNJpaucvzhYnV9ojBtNqauS75BtIZlu/mS+Sgq6RZME/7cnGmeQn8pPK3KyGDq2Iiv59JigbI3jcZqMcLiA67W7JR0YTOjTfNVHhf2TqKbaxMOOnlcPYzqA1853gCxoE8ek5QUy3zWehJRQQeumPU72uMt0j8=
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
after_deploy:
- bash deploy.sh
notifications:
  email: false
  slack:
    rooms:
    - secure: mZtB5m84TEovyP1PWka1NDMI/F/Tk1EFPDAsPlozNNUfcGihXcjuPWM7gtQ20WsJwlxQf39/RECPu1T6vkkDfyLgJsYeUIet7MzCSsglIEAL1vpGiLNodIA10qboSM6KzOrkz9rXi4rv+676bmOzkGT/q+6KJRgWfo2z3OlOk3y+AfBn1EeAPFizpqVCZERrwb8nOxWhucSOnTyYHG/art4UKshPze8jzXa/tr/ExQppHhxbrS6SkKBK/hVMgBCNQIDJa+OMFQ/LM9uKeZ/hERkCZGDawgQufwIUN/rCLSXbO+AharysIn6/HP99sbX4I+APqt7+9f0LEca1KeGYCFSk1y6NAsLBdMj+0mfQaVZX3Y4vZ/hXGcFllMXKW8Cq3rcHAIYfvbI+6bFeffp4zpRyHXqIoLJ1XDnVg2vJ38UmRDO4tjUOz1LhMEgu0FF4bhtDvw0gIs/8pTF0m9rZ7S2J1TDKpI5CYiD93uTjVOH79I/WZfsFp5Ce5rv5+VUZ8wTBEn++LlA/1cQobJqWF6A5kkViuJbLikPckQm1dHpFB7EL2G2CpZTGekTYCRikCvZPES1bsmWV1uy9H5aSDuzJMJaomOKyhMLZhbSeQZ0DZpj1MUFjf49F0eYFD6c/iMtFEgPryYcfisI/fOz+WAIGg5+Um9DR2LHUarzOjdA=
    - secure: d7jKGSmjmzdgmhN1taGCck6Vzvu6xVxhVIgkVJpk91WrssuG2qz01ub57Luwq01nHGQV2Ns1IA5Y9Szt5lU0CVSDzHu5PS2wiLMaxteWB5s4o4EhoxdoM4c8mlK7yHmcQ4sxfhcMuNqvzBlmkBBZAuKgJl/n17fcnwPYngu6cHPxSyZ9ODtKkCtP6btY2vTqNwGv3lpH+aSzFXTZFxt8GIhz3bUTfxyL19nJU3TO217KBRVnmdP3gFREfVfsoFFYp0Msj/4Dla1RumBZ6a34ibb7aahQ+h32Q067aN1Af6eft67wnreea8HNwZMggYVtQGEvJSUMO79RLcERTvGFPjSfXFFDy1FCuWvWJIOyqDRRcifTB0lGg/MIrUuT75YsEGwCalzmjxox3qXWyaO8gBpuFCCBDJuqy6VSTQLxJc6FXfZAhBiD49Fcp5OM4SSbnM3mxMxc5e/ij8LLPfHwmqSzeWX9C7GinsP5UHjMZzPFLi7Uj+LpToMe4lLnYkmXjQrAyecfsx0AHwZ/Guk7DybwV+VSPHx9TqxJ9KogHfRTfk9XTvujvoBDmRFzAWim16fDZvVABBJkqL4XcxHvZM0j18w0lpth+7uFHZZoZscD9/J5d0ysDjYF4ZskbsRIOBLfSEnoem67mC3Z1ThXthApCd39yrKs5QYzGsHbrgY=
  webhooks:
  - https://webhook.atomist.com/travis
