sudo: false
language: python

python:
 - 3.5

install:
 - pip install -r requirements.txt

script:
 - mkdocs build

after_success:
 - bash ./deploy.sh

env:
  global:
    - GITHUB_REPO: atomisthq/atomisthq.github.io
    - secure: "OmJKNY9T9aUfl9+mxkiiH8T8Eqv6iW1P2PVlHed+Aj/6Inq766JYtiNjvJbwJTzES1yaLjIFoVANrs7MmXXXU432VTqKRWM5q1EErmAdVSxAPrDM803sqtFgPo5DnXUf0LRRZTA0umuwivIxBx7kFumy7B7OsuOwLOIMPMyornAnphc+Hy4pdIF7pW6v3wzAcRBRGEqLWo70srbT19mpYn2hdCrtE+zApsrW34NjxZAAFWcQgpWrtaUocgpytzh67R7uyhu4ketr/e+NRE6HOPb+kYsLRNO5eo6NKeHRNd0i0wfZ6QiZ/1jBTMqiM1i1NkF1kFl7ZqBAgYRIhciyU/EMIBnwT5VQQ1YWcL25JmEO9X9KgmFaJTBw7gyFn/AfPzDkT3slFjcNCNd/y/kG+6TPz0UWXUS2O0aXFQ3c2+PVH0jUV5AXkldiSSHRmWNusfmbIqhi07uXkyfsqEczEc1ONfWTOzKMwjXe80wM4eMKtIc2rjbPjEo/mPl+Kh0lUkRtAALXG8jEf8qvX1tR70Kl4VXGytjtOfBuBjmL1jYkRV5UKja5zozmDHMENfYgHhj/D0wFvo0zIdAac+alb4RpuGayxwVeQTFULWv3OkXm34FXyAnq4SaGkz6ey4m+jQ9kAZNlaGZ1F/SvD+l53AFxdAcK/3R4O2kECzpQ9Co="