sudo: false
language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt 

script:
  - bash ./deploy.sh

env:
  global:
    - secure: ZEU2ODZq3k/5lMRWwAx5wr07N70s8hRf61Aq+VcFMJYbNy5ZPPvi96Bq14HIbOcpAP9fTMivyf7xg86hDf8+ca8JV72ghSDt2BK4tYph0qxJ396a1S4EFrKltF54OzjGeN/l8v89IpLPMcriAkAkerjy1VI4tza+6PMi8TG25Tz3aQPGt8EQ7tC/c8iY0Lo5NRFjGiUSnbKfCa/ulnXfiTnMxxZpo3FKBrj0UNxnFfm8BqaBezkoSP9jQraMOJTBLTNoMdWKWBsSijWn8U0nK//2DSvTTSvk/LG48isS1y6f7lLN5hkcmUElZKouN5Mqy7XJuysQLNwGZ+LQPZFcQvnlsHLZoeaGW3Cgg4Wmpk8Cop1LNWXhdG9KoSFcWqLGGuc0oXAVrts87f1Hjl7yOV8bCEbufCW/Rzc1qu2lVv3+jzZ9lq8wmn5YTgC9d8oP4K2vv35/gTjIwg1/Wi62dpTjvtJfBKMx4VK/zjf2YxHcb/EMIbn7pnTCDn0MkDhTbOxbPwbDyIaLQtgM5MbY7wCQCHwp0iq7rei33SO7A0TLCrbLRRR2eWTGAvhDPcHHvU7XrXTUzJCSaFTzaWCAfZKPC5tOtXeEv40uO0qNe41AEMgc67QLfPEBN/QffL252cTcRB90J0UmV7HlCZCKmnd/Nv3XnaIIZyrqN1+L8k4=
    - GITHUB_REPO: "atomisthq/atomisthq.github.io"