sudo: false
language: python
python:
- 3.5
install:
- pip install -r requirements.txt
script:
- bash ./deploy.sh
env:
  global:
  - GITHUB_REPO: atomisthq/atomisthq.github.io
  - secure: Ai6i3qjHGJ+JfWPoLjIZV7V23kKtLw2T795H4veMcvR04+zHjf2cYAbYzpU9WirtLJ+fH4xfBLauGox4vB9K0bXsDXLSx/lUpfQVsEueDDFCWBOyzEUgifkXmgBRWBrVkc5MGQbdFII897QbvG112KBM83FfmA1slBnXWJt9ymfmOZAuhD71lxbVqGOuDi+zoOD2F1Sjx1XnldZg6Yezx3sGa/vWo5xCn+icw3uJwl8VjVQ5tFnpPGXW/BUhYRHt5i+0Sdeh4QnqLHeJb0vYjohqcKgnJSzw6kFuvLXaCq7NtI1OSMDXaUw05DjK0v5b/b5ONTWzJHt0nPXZ1wRKMY1tXcujZsV5KpYSJYxL6d2OFdKEacWJ3/pvcV+76ixNADP0zOQPEUl/RBCtGIP8p+aXxIeOzNz9kz+2cZrZkTC9grHVatNPnYmW/rbYu5bJqZMe0F3BybGU7Rk8N8CavOLKsdGVw+nqaSuQDV6VlBpaN7gyeo2vhnaz7WhbFu9eBPtCY8eZGBId54VJxmg2tGXWscsz4+t87Bhi//V+/fEyGQQDMTZntYYUa40BB/SfoRMCZ2D9WkkmvhB8gStruKbkFjKh8MDhEqvId2HsuUYhKn0JkAp0fWkPad4+LA0zOrNLuazJM0Pjc35JEy/BtAuG2j9Bcrdoq7PRefOtW54=
