site_name: The Atomist Documentation
copyright: 2016, Atomist
theme_dir: atomist
pages:
- Welcome to Atomist: 'index.md'
- Quick Starts:
  - Introduction: 'quick-starts/index.md'
  - Enrolling your team with Atomist: 'quick-starts/enrollment.md'
  - Create a new Project based on a Template: 'quick-starts/create-new-project.md'
  - List Available Atomist Project Templates: 'quick-starts/project-templates/list-project-templates.md'
  - Create Atomist Project Templates: 'quick-starts/project-templates/new-project-template.md'
  - Create a new Project Project Template based on Forking an existing Template: 'quick-starts/project-templates/new-project-template-from-fork.md'
  - Create a new Project Template from Scratch: 'quick-starts/project-templates/new-project-template-from-scratch.md'
  - Extract a Microservice: 'quick-starts/extract-microservice.md'
  - Deleting and Tidying Up a Microservice: 'quick-starts/delete-microservice.md'
- Reference Documentation:
  - Introduction: 'reference-docs/index.md'
  - Atomist Bot Commands: 'reference-docs/bot-commands.md'
  - Overview of Atomist Project Templates: 'reference-docs/project-templates-overview.md'
  - Current Systems Atomist integrates with: 'reference-docs/current-system-integrations.md'
