site_name: The Atomist Documentation
copyright: 2016, Atomist
theme_dir: atomist
extra_css:
  - "css/brandon-grotesque.css"
pages:
- Welcome to Atomist: 'index.md'
- Quick Starts:
  - Introduction: 'quick-starts/index.md'
  - Enrolling your team with Atomist: 'quick-starts/enrollment.md'
  - Create a new Project based on a Template: 'quick-starts/create-new-project.md'
  - List Available Atomist Project Templates: 'quick-starts/project-templates/list-project-templates.md'
  - Create Atomist Project Templates: 'quick-starts/project-templates/new-project-template.md'
  - Create a new Project Project Template based on Forking an existing Template: 'quick-starts/project-templates/new-project-template-from-fork.md'
  - Create a new Project Template from Scratch: 'quick-starts/project-templates/new-project-template-from-scratch.md'
  - Working Locally with Atomist Project Templates and the Atomist Shell: 'quick-starts/project-templates/shell/project-operations-shell-quickstarts.md'
  - Getting Set Up with the Atomist Shell: 'quick-starts/project-templates/shell/getting-started-with-the-shell.md'
  - Creating a new new project based on a local Atomist Project Template with the Atomist Shell: 'quick-starts/project-templates/shell/creating-a-local-project-based-on-local-template.md'
  - Constructing and executing an Atomist Editor that can work on an existing project with the Atomist Shell: 'quick-starts/project-templates/shell/your-first-editor.md'
  - Calling an Atomist Project Editor from another Editor: 'quick-starts/project-templates/shell/calling-an-editor.md'
  - Extract a Microservice: 'quick-starts/extract-microservice.md'
  - Deleting and Tidying Up a Microservice: 'quick-starts/delete-microservice.md'
- Reference Documentation:
  - Introduction: 'reference-docs/index.md'
  - The Atomist Bot: 'reference-docs/bot.md'
  - Overview of Atomist Project Templates: 'reference-docs/project-templates/project-templates-overview.md'
  - Overview of Atomist Project Templates Content: 'reference-docs/project-templates/project-template-contents-overview.md'
  - Contents of the Meta Directory: 'reference-docs/project-templates/project-templates-meta-contents.md'
  - Contents of the Project Directory: 'reference-docs/project-templates/project-templates-project-contents.md'
  - How Atomist Project Templates are Used: 'reference-docs/project-templates/how-project-templates-are-used.md'
  - Introduction to Atomist Project Editors: 'reference-docs/project-editors.md'
  - Authoring Atomist Project Editors and Reviewers with the Atomist DSL: 'reference-docs/rug.md'
  - Test-Driven Atomist Project Editors, Generators and Reviewers with the Atomist DSL Test Framework: 'reference-docs/rug-test.md'
  - Command Line Tooling for Project Operations: 'reference-docs/cli.md'
  - Current Systems Atomist integrates with: 'reference-docs/current-system-integrations.md'
  - Current Rug DSL Type Reference: 'reference-docs/rug-kinds.md'