site_name: The Atomist Documentation
site_description: Documentation for the Atomist Developer Platform
site_author: The Atomist Team
copyright: '&copy; 2017 Atomist, Inc.'
extra:
  main_site_url: 'https://www.atomist.com/'
theme: material
site_favicon: images/favicon.ico
extra:
  logo: 'images/atomist-logo-horiz-reversed.svg'
  palette:
    primary: 'green'
    accent: 'green'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/atomist'
    - type: 'twitter'
      link: 'https://twitter.com/atomist'
    - type: 'slack'
      link: 'https://join.atomist.com/'
extra_css:
  - 'stylesheets/extra.css'
google_analytics:
  - 'UA-74966852-1'
  - 'auto'
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false, linenums=false)
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
repo_name: 'Rug'
repo_url: 'https://github.com/atomist/rug'
pages:
- Overview:
  - Introduction: index.md
  - Concepts: concepts.md
  - Capabilities: capabilities.md
- Getting Started:
  - Overview: 'getting-started/index.md'
  - Prerequisites: 'getting-started/prerequisites.md'
  - Invite Atomist to Slack: 'getting-started/invite-atomist-to-slack.md'
  - Connect Atomist to GitHub: 'getting-started/connect-atomist-to-github.md'
  - Putting Atomist to Work: 'getting-started/putting-atomist-to-work.md'
  - Connect Atomist to CI: 'getting-started/connect-atomist-to-ci.md'
  - Build Your Own Development Automation: 'getting-started/build-your-own-development-automation.md'
- Guides:
  - Introduction: 'guides/index.md'
  - Buttons: 'guides/buttons.md'
  - Atomist Bot: 'guides/bot.md'
  - Rug CLI: 'guides/rug-cli.md'
  - Rug TypeScript: 'guides/rug-typescript.md'
- Atomist in Depth:
  - Introduction: 'atomist/index.md'
  - Rug:
    - Introduction : 'atomist/rug/index.md'
    - Handlers: 'atomist/rug/handlers.md'
    - Commands: 'atomist/rug/commands.md'
    - Editors: 'atomist/rug/editors.md'
    - Generators: 'atomist/rug/generators.md'
    - Predicates: 'atomist/rug/predicates.md'
    - Reviewers: 'atomist/rug/reviewers.md'
    - Executors: 'atomist/rug/executors.md'
    - Path Expressions: 'atomist/rug/path-expressions.md'
    - Microgrammars: 'atomist/rug/microgrammars.md'
    - Templates: 'atomist/rug/templates.md'
    - Tests: 'atomist/rug/tests.md'
    - Archives: 'atomist/rug/archives.md'
    - Lifecycle: 'atomist/rug/lifecycle.md'
    - Conventions: 'atomist/rug/conventions.md'
  - Integrations:
    - Overview: 'atomist/integrations/index.md'
    - GitHub.com: 'atomist/integrations/github.md'
    - Travis CI: 'atomist/integrations/travis-ci.md'
  - Cortex: 'atomist/cortex.md'
  - Interfaces:
    - Introduction: 'atomist/interfaces/index.md'
    - Chat: 'atomist/interfaces/chat.md'
    - Rug CLI:
      - Overview: 'atomist/interfaces/cli/index.md'
      - Installation: 'atomist/interfaces/cli/install.md'
    - Button: 'atomist/interfaces/button.md'
- Reference Documentation:
  - Overview: 'reference/index.md'
  - Rug:
    - Introduction: 'reference/rug/index.md'
    - Handlers: 'reference/rug/handlers.md'
    - Commands: 'reference/rug/commands.md'
    - Editors: 'reference/rug/editors.md'
    - Generators: 'reference/rug/generators.md'
    - Predicates: 'reference/rug/predicates.md'
    - Reviewers: 'reference/rug/reviewers.md'
    - Executors: 'reference/rug/executors.md'
    - Path Expressions: 'reference/rug/path-expressions.md'
    - Microgrammars: 'reference/rug/microgrammars.md'
    - Templates: 'reference/rug/templates.md'
    - Tests: 'reference/rug/tests.md'
    - Archives: 'reference/rug/archives.md'
    - Language Extensions:
      - Introduction: 'reference/rug/extensions/index.md'
      - CljProject: 'reference/rug/extensions/clj-project.md'
      - CSharpFile: 'reference/rug/extensions/c-sharp-file.md'
      - DockerFile: 'reference/rug/extensions/docker-file.md'
      - ElmModule: 'reference/rug/extensions/elm-module.md'
      - EveryPom: 'reference/rug/extensions/every-pom.md'
      - File: 'reference/rug/extensions/file.md'
      - JavaProject: 'reference/rug/extensions/java-project.md'
      - JavaSource: 'reference/rug/extensions/java-source.md'
      - JavaType: 'reference/rug/extensions/java-type.md'
      - Json: 'reference/rug/extensions/json.md'
      - Line: 'reference/rug/extensions/line.md'
      - Pom: 'reference/rug/extensions/pom.md'
      - Project: 'reference/rug/extensions/project.md'
      - Properties: 'reference/rug/extensions/properties.md'
      - PythonFile: 'reference/rug/extensions/python-file.md'
      - PythonRequirementsTxt: 'reference/rug/extensions/python-requirements-txt.md'
      - RugArchiveProject: 'reference/rug/extensions/rug-archive-project.md'
      - RugFile: 'reference/rug/extensions/rug-file.md'
      - ScalaFile: 'reference/rug/extensions/scala-file.md'
      - Services: 'reference/rug/extensions/services.md'
      - SpringBootProject: 'reference/rug/extensions/spring-boot-project.md'
      - Xml: 'reference/rug/extensions/xml.md'
      - Yml: 'reference/rug/extensions/yml.md'
    - DSL:
      - Introduction: 'reference/rug/dsl/index.md'
      - Syntax: 'reference/rug/dsl/syntax.md'
      - Escaping Rug into JavaScript: 'reference/rug/dsl/javascript.md'
  - Integrations: 'reference/integrations.md'
  - Rug CLI Command Reference: 'reference/rug-cli/index.md'
