site_name: The Atomist Documentation
site_description: Documentation for the Atomist Development Automation Platform
site_author: The Atomist Team
copyright: '&copy; 2017 Atomist, Inc.'
extra:
  main_site_url: https://www.atomist.com/
theme:
  name: material
  favicon: 'img/favicon.ico'
  logo: img/atomist-logo-horiz-reversed.svg
  palette:
    primary: blue grey
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
extra:
  social:
    - type: medium
      link: https://the-composition.com/
    - type: github
      link: https://github.com/atomist
    - type: twitter
      link: https://twitter.com/atomist
    - type: slack
      link: https://join.atomist.com/
extra_css:
  - stylesheets/extra.css
google_analytics:
  - UA-74966852-1
  - auto
markdown_extensions:
  - markdown_include.include:
      base_path: "docs/common"
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - def_list
  - footnotes
  - meta
  - smarty
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
# repo_name: Rug
# repo_url: https://github.com/atomist/rug

pages:
  - Introduction: index.md
  - Using Atomist: user/index.md
  - Developer Guide:
      - Overview: developer/index.md
      - Prerequisites: developer/prerequisites.md
      - Quick Start: developer/quick-start.md
      - Commands: developer/commands.md
      - Events: developer/events.md
      - Slack Messages: developer/slack.md
      - Working with GraphQL: developer/graphql.md
      - Automation Client: developer/client.md
      - Running Automation Clients: developer/run.md
      - Move This: developer/create.md
  - Support: support.md
