site_name: The Atomist Documentation
site_description: Documentation for the Atomist Developer Platform
site_author: The Atomist Team
copyright: '&copy; 2017 Atomist, Inc.'
extra:
  main_site_url: 'https://www.atomist.com/'
theme: material
#theme_dir: atomist
site_favicon: images/favicon.ico
extra:
  logo: 'images/atomist-logo-horiz-reversed.svg'
  palette:
    primary: 'green'
    accent: 'green'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/atomist'
    - type: 'twitter'
      link: 'https://twitter.com/atomist'
    - type: 'slack'
      link: 'https://join.atomist.com/'
extra_css:
  - 'stylesheets/extra.css'
google_analytics:
  - 'UA-74966852-1'
  - 'auto'
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false, linenums=true)
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
repo_name: 'Rug'
repo_url: 'https://github.com/atomist/rug'
pages:
- Welcome to Atomist: 'index.md'
- Quick Starts:
  - Introduction: 'quick-starts/index.md'
  - Buttons: 'quick-starts/buttons.md'
  - Atomist Bot: 'quick-starts/bot.md'
  - Rug CLI: 'quick-starts/rug-cli.md'
  - Rug TypeScript: 'quick-starts/rug-typescript.md'
- Rug:
  - Why and What is Rug? : 'rug/why-and-what-is-rug.md'
  - Rug Language: 'rug/rug-dsl.md'
  - What Goes in a Rug Archive?: 'rug/rug-archive.md'
  - A Day in the Life of a Rug Archive: 'rug/rug-lifecycle.md'
  - Rug CLI:
    - Introduction: 'rug/rug-cli/index.md'
    - Rug CLI Installation: 'rug/rug-cli/rug-cli-install.md'
- Reference Documentation:
  - Introduction: 'reference-docs/index.md'
  - Rug:
    - Introduction: 'reference-docs/rug/index.md'
    - Rug Tests: 'reference-docs/rug/rug-tests.md'
    - Rug Editors: 'reference-docs/rug/rug-editors.md'
    - Rug Generators: 'reference-docs/rug/rug-generators.md'
    - Rug Templates: 'reference-docs/rug/rug-templates.md'
    - Rug Predicates: 'reference-docs/rug/rug-predicates.md'
    - Rug Language Extensions:
      - Introduction: 'reference-docs/rug/extensions/index.md'
      - Project: 'reference-docs/rug/extensions/rug-core-types-project.md'
      - JavaProject: 'reference-docs/rug/extensions/rug-core-types-java-project.md'
      - SpringBootProject: 'reference-docs/rug/extensions/rug-core-types-spring-boot-project.md'
      - CljProject: 'reference-docs/rug/extensions/rug-core-types-clj-project.md'
      - RugArchiveProject: 'reference-docs/rug/extensions/rug-core-types-rug-archive-project.md'
      - Line: 'reference-docs/rug/extensions/rug-core-types-line.md'
      - File: 'reference-docs/rug/extensions/rug-core-types-file.md'
      - Xml: 'reference-docs/rug/extensions/rug-core-types-xml.md'
      - Pom: 'reference-docs/rug/extensions/rug-core-types-pom.md'
      - EveryPom: 'reference-docs/rug/extensions/rug-core-types-every-pom.md'
      - Yml: 'reference-docs/rug/extensions/rug-core-types-yml.md'
      - Properties: 'reference-docs/rug/extensions/rug-core-types-properties.md'
      - Json: 'reference-docs/rug/extensions/rug-core-types-json.md'
      - PackageJson: 'reference-docs/rug/extensions/rug-core-types-package-json.md'
      - JavaSource: 'reference-docs/rug/extensions/rug-core-types-java-source.md'
      - JavaType: 'reference-docs/rug/extensions/rug-core-types-java-type.md'
      - CSharpFile: 'reference-docs/rug/extensions/rug-core-types-c-sharp-file.md'
      - ElmModule: 'reference-docs/rug/extensions/rug-core-types-elm-module.md'
      - DockerFile: 'reference-docs/rug/extensions/rug-core-types-docker-file.md'
      - PythonFile: 'reference-docs/rug/extensions/rug-core-types-python-file.md'
      - PythonRequirementsTxt: 'reference-docs/rug/extensions/rug-core-types-python-requirements-txt.md'
      - Services: 'reference-docs/rug/extensions/rug-core-types-services.md'
    - Escaping Rug into JavaScript: 'reference-docs/rug/escape/rug-javascript.md'
    - Rug CLI Command Reference: 'reference-docs/rug/rug-cli-commands.md'
    - Rug Conventions: 'reference-docs/rug/rug-conventions.md'
  - Atomist Integrations: 'reference-docs/system-integrations.md'
