site_name: The Atomist Documentation
copyright: 2016, Atomist
theme_dir: atomist
site_favicon: images/favicon.png
extra_css:
  - "css/brandon-grotesque.css"
pages:
- Welcome to Atomist: 'index.md'
- Quick Starts:
  - Introduction: 'quick-starts/index.md'
- Reference Documentation:
  - Introduction: 'reference-docs/index.md'
  - Current Systems Atomist integrates with: 'reference-docs/current-system-integrations.md'
